
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
"aws_project_region": "us-east-1",
"aws_cognito_identity_pool_id": "us-east-1:bb0786bf-d204-4943-a28b-f46f6f426d33",
"aws_cognito_region": "us-east-1",
"aws_user_pools_id": "us-east-1_wd3ckcMB5",
"aws_user_pools_web_client_id": "3a8ta8qat8h5v8aiap1h9u8n8",
"oauth": {
"domain": "likerbackendslab6b66b17-b6b66b17-dev.auth.us-east-1.amazoncognito.com",
"scope": [
"phone",
"email",
"openid",
"profile",
"aws.cognito.signin.user.admin"
],
"redirectSignIn": "http://localhost:3000/signup/",
"redirectSignOut": "http://localhost:3000/logout/",
"responseType": "code"
},
"federationTarget": "COGNITO_USER_POOLS",
"aws_appsync_graphqlEndpoint": "https://hwczvz6fyjckfgrdqzd3inutqu.appsync-api.us-east-1.amazonaws.com/graphql",
"aws_appsync_region": "us-east-1",
"aws_appsync_authenticationType": "API_KEY",
"aws_appsync_apiKey": "da2-o4bcz5w3zfb6hfb65gnwnmh4ba",
"aws_cloud_logic_custom": [
{
"name": "triblePostInsertAPI",
"endpoint": "https://f3ks9ci145.execute-api.us-east-1.amazonaws.com/dev",
"region": "us-east-1"
}
],
"aws_user_files_s3_bucket": "likerslastaticbuckte15616-dev",
"aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;